<a href="https://colab.research.google.com/github/rubaabirami/Python/blob/main/Google_collab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

System specification

In [ ]:
!cat /proc/cpuinfo


processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
ad

In [ ]:
!cat /proc/meminfo

MemTotal:       13289424 kB
MemFree:         9369624 kB
MemAvailable:   12164228 kB
Buffers:          138276 kB
Cached:          2851208 kB
SwapCached:            0 kB
Active:           468116 kB
Inactive:        3231100 kB
Active(anon):       1736 kB
Inactive(anon):   710584 kB
Active(file):     466380 kB
Inactive(file):  2520516 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               300 kB
Writeback:             0 kB
AnonPages:        709784 kB
Mapped:           435900 kB
Shmem:              2580 kB
KReclaimable:      97292 kB
Slab:             133996 kB
SReclaimable:      97292 kB
SUnreclaim:        36704 kB
KernelStack:        5236 kB
PageTables:        11880 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6644712 kB
Committed_AS:    2711244 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       11860 kB
VmallocChunk:    

Installing libraries

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd


In [ ]:
df =pd.read_csv('/content/HousingData.csv')

In [ ]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90    NaN  36.2

In [ ]:
print('Machine learning')

Machine learning


In [ ]:
!ls

HousingData.csv  sample_data


Programming language used for machine learning:
1.Python
2.R

#Print function

In [ ]:
print("Machine learning")

Machine learning


In [ ]:
print("Machine learning" + " projects")

Machine learning projects


In [ ]:
print(8)

8


In [ ]:
print(8+3)

11


Basic data Types


1.int
2.float
3.str


In [ ]:
type(8)

int

In [ ]:
type(5.3)


float

In [ ]:
type("English")

str

4.complex
5.booleen

In [ ]:
#complex numbers
c=1+ 3j
print(c)
type(c)

(1+3j)


complex

In [ ]:
#int to float
x=10
print(x)
type(x)
y= float(x)
print(y)
type(y)

10
10.0


float

In [ ]:
#float to int
x=5.8
print(x)
type(x)

5.8


float

In [ ]:
y=int(x)
print(y)
type(y)

5


int

Boolean
1.true
2.false

In [ ]:
a=True
print(a)
type(a)

True


bool

In [ ]:
b=False
print(b)
type(b)

False


bool

In [ ]:
a= 7<3
print(a)
type(a)

False


bool

In [ ]:
print("hello" * 5)

hellohellohellohellohello


Slicing

In [ ]:
my_string="programming"

In [ ]:
print(my_string[1:5])

rogr


In [ ]:
print(my_string[0:10:2])

pormi


String concatenation

In [ ]:
word_1="Machine"
word_2="Learning"
print(word_1 + word_2)

MachineLearning


#constant and variable

In [ ]:
superhero = "iron man"
print(superhero)

iron man


In [ ]:
super_hero = "iron man"
print(super_hero)

iron man


In [ ]:
hero1,hero2,hero3= "ironman","captain america","batman"
print(hero1)
print(hero2)
print(hero3)

ironman
captain america
batman


In [ ]:
x=y=z= 23
print(x)

23


#Input function

In [ ]:
number_1= input("Enter first number:")
number_2= input("Enter second number:")
sum= number_1 + number_2
print(sum)

Enter first number:10
Enter second number:20
1020


In [ ]:
number_1= int(input("Enter first number:"))
number_2= int(input("Enter second number:"))
sum= number_1 + number_2
print(sum)

Enter first number:10
Enter second number:20
30


In [ ]:
# changing the data type in python:
num =5
print(float(num))

5.0


Types of object in Python
1.Immutable objects #value cannot be changed once created
a.int
b.float
c.bool
d.string
e.tuple
2.Mutable object: #value can be changed after creation
a.List
b.Set
c.Dictionary

List:
Lists are used to store multiple items in a single variable.

Lists are one of 4 built-in data types in Python used to store collections of data, the other 3 are Tuple, Set, and Dictionary, all with different qualities and usage.

Lists are created using square brackets.
List can contain multiple datatypes.


List items are ordered, changeable, and allow duplicate values.

In [ ]:
my_list=[1,2,3,4,5]
print(my_list)
type(my_list)


[1, 2, 3, 4, 5]


list

In [ ]:
my_list=[2,3,1.8,'english',True]
print(my_list)

[2, 3, 1.8, 'english', True]


In [ ]:
#list are mutable--> changable
my_list=[2,3,1.8,'english',True]
my_list.append(6)
print(my_list)

[2, 3, 1.8, 'english', True, 6]


In [ ]:
print(my_list[0])
print(my_list[2])

2
1.8


In [ ]:
#list allow duplicate values
list_1=[1,2,3,4,5,12,2,3]
print(list_1)

[1, 2, 3, 4, 5, 12, 2, 3]


In [ ]:
print(len(list_1))

8


In [ ]:
#initiating an empty list
list_2=[]
print(list_2)

[]


In [ ]:
list_2.append(5)
print(list_2)

[5]


In [ ]:
#del an item on list
list_2=[1,2,3,4,5,6]
print(list_2)
del list_2[2]
print(list_2)

[1, 2, 3, 4, 5, 6]
[1, 2, 4, 5, 6]


In [ ]:
#join two list
list_3=[1,2,3,4]
list_4=[5,6,7,8]
list_5=list_3 + list_4
print(list_5)

[1, 2, 3, 4, 5, 6, 7, 8]


Tuples:
Tuples are used to store multiple items in a single variable.

Tuple is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Set, and Dictionary, all with different qualities and usage.

A tuple is a collection which is ordered and unchangeable.

Tuples are written with round brackets.

In [ ]:
tuple_1=(2,3,4,5)
print(tuple_1)
type(tuple_1)

(2, 3, 4, 5)


tuple

In [ ]:
#converting list to tuple
my_list=[3,4,5,6]
print(my_list)
my_tuple=tuple(my_list)
print(my_tuple)

[3, 4, 5, 6]
(3, 4, 5, 6)


Tuples are immutable -->unchangable

In [ ]:
my_tuple.append(6)

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
print(len(my_tuple))

4


Set:
Sets are used to store multiple items in a single variable.

Set is one of 4 built-in data types in Python used to store collections of data, the other 3 are List, Tuple, and Dictionary, all with different qualities and usage.

A set is a collection which is unordered, unchangeable*, and unindexed.
Sets are written with curly brackets.
Set items are unordered, unchangeable, and do not allow duplicate values.

In [ ]:
#set--> curly brackets
my_set={1,2,3,4,5}
print(my_set)
type(my_set)

{1, 2, 3, 4, 5}


set

In [ ]:
#unindexed
print(my_set[0])

TypeError: 'set' object is not subscriptable

In [ ]:
#converting list to set
my_list=[2,3,4,5,6]
print(my_list)
my_set=set(my_list)
print(my_set)


[2, 3, 4, 5, 6]
{2, 3, 4, 5, 6}


In [ ]:
#set doesnot allow repeated value
set_1={1,2,3,4,5,1,2,3}
print(set_1)

{1, 2, 3, 4, 5}


Dictionary:
Dictionaries are used to store data values in key:value pairs.

A dictionary is a collection which is ordered*, changeable and do not allow duplicates.
Dictionaries are written with curly brackets, and have keys and values.
Dictionaries are changeable, meaning that we can change, add or remove items after the dictionary has been created.

In [ ]:
#key pair values
my_dictionary={"name":"john","age":34}
print(my_dictionary)
type(my_dictionary)

{'name': 'john', 'age': 34}


dict

In [ ]:
print(my_dictionary['name'])


john


Operators in python:


1.   Arithmetic Operator
2.   Assignment Operator

1. Comparison Operator
2.   Logical Operator

1.   Identity Operator
2.  Membership Operator










1.Arithmetic Operator

In [ ]:
num_1=20
num_2=30
#addition
sum=num_1 +num_2
print('sum=',sum)

sum= 50


If-else statement

In [ ]:
a=30
b=50
if (a>b):
  print("a is greater than b")
else:
  print("b is greater than a")


b is greater than a


In [ ]:
a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
if (a>b):
  print("a is greater than b")
else:
  print("b is greater than a")

Enter first number:15
Enter second number:30
b is greater than a


In [ ]:
a=15
b=40
c=35
if (b<a>c):
  print("a is the greatest number")
elif (a<b>c):
  print("b is the greatest number")

b is the greatest number


Loops in Python

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for x in range(6):
  print(x)


0
1
2
3
4
5


In [ ]:
for i in range(5):
  laptop_price=[40000,50000,60000,70000,80000]
  print(laptop_price[i])


40000
50000
60000
70000
80000


In [ ]:
for i in range(6):
  laptop_price= int(input("Enter laptop price:"))
  print(laptop_price)

Enter laptop price:1000
1000
Enter laptop price:200000
200000
Enter laptop price:300000
300000
Enter laptop price:400000
400000
Enter laptop price:500000
500000
Enter laptop price:55000
55000


In [ ]:
numbers = [500,400,300,590]
for i in numbers:
  print(i)

500
400
300
590


Functions:
Function is a block of code that can be resued in program

In [ ]:
#factorial
number=int(input("Enter a number:"))
factorial=1
if number==0:
  print("The factorial of 0 is 1")
else:
  for i in range(1,number+1):  #range(1,6)
    factorial=factorial*i
  print('the factorial of',number,'is',factorial)

Enter a number:5
the factorial of 5 is 120


In [ ]:
def factorial(n):
    fact = 1
    for i in range(1, n + 1):
        fact *= i
    return fact

# Example
num = int(input("Enter a number: "))
print("Factorial:", factorial(num))



Enter a number: 5
Factorial: 120


#NumPy-Numerical python--->
Advantage of numpy arrays:
1.   Allows several mathematical operations
2.   fast operations



In [3]:
import numpy as np


List vs numpy -Time taken

In [4]:
from time import process_time

Time taken by a list

In [5]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0003047709999997039


In [10]:
np_array = np.array([i for i in range(10000)])
start_time=process_time()
np_array += 5
end_time=process_time()
print(end_time - start_time)

0.00011633100000008056


Numpy arrays


In [11]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [12]:
np_array =np.array([1,2,3,4,5])
print(np_array)
type(np_array)


[1 2 3 4 5]


numpy.ndarray

In [13]:
#creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [14]:
a.shape #give rows and coloumn

(4,)

In [17]:
#creating 2D array
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
b.shape

(2, 4)

In [19]:
c =np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Inital Placeholders in numpy arrays

In [21]:
#create a numpy array  of zeros
x= np.zeros((4,5)) #4 rows 5 col with value 0
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
#create a numpy array of ones
y= np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
#create array of particular value
z= np.full((5,4),5) #4 row 5 col with all values 5
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [24]:
#to create an identity matrix[same row same col]--> eye(matrix size)
#all diagonal value is 1
a= np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
#create numpy array with random value(vaue between 0-1)
b= np.random.random((3,4)) # 3r 4c
print(b)

[[0.62284861 0.45613664 0.44522873 0.92397656]
 [0.0954372  0.60333993 0.05651222 0.10613941]
 [0.90635119 0.21536736 0.63508788 0.47751717]]


In [27]:
# random integer values array within a specific range
c=np.random.randint(10,100,(3,5)) # any  value between 10 to 100 in 3*5 matrix
print(c)

[[65 52 38 65 42]
 [79 31 54 56 83]
 [78 67 63 28 65]]


In [29]:
#array evenly spaced values --> specifying the step
e= np.linspace(10,30,5) #start,end,step
print(e)

[10. 15. 20. 25. 30.]


In [31]:
d=np.arange(10,30,5)
print(d)

[10 15 20 25]


Analysing a numpy array

In [32]:
c=np.random.randint(10,90,(5,5))
print(c)

[[22 66 15 39 81]
 [12 13 68 41 51]
 [16 15 67 37 50]
 [71 18 41 73 63]
 [75 55 11 27 40]]


In [33]:
print(c.shape)

(5, 5)


In [34]:
#number of dimension
print(c.ndim)

2


In [35]:
print(c.size)

25


In [36]:
print(c.dtype) #64bit data val

int64


Mathematical oper

In [37]:
a= np.random.randint(0,10,(3,3))#value bet 0-10 in3*3 matrix
b= np.random.randint(10,20,(3,3))#value bet 10-20 in3*3 matrix
print(a)
print(b)

[[1 8 8]
 [0 8 9]
 [9 2 2]]
[[10 19 11]
 [13 10 15]
 [19 18 15]]


In [38]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[11 27 19]
 [13 18 24]
 [28 20 17]]
[[ -9 -11  -3]
 [-13  -2  -6]
 [-10 -16 -13]]
[[ 10 152  88]
 [  0  80 135]
 [171  36  30]]
[[0.1        0.42105263 0.72727273]
 [0.         0.8        0.6       ]
 [0.47368421 0.11111111 0.13333333]]


In [39]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[11 27 19]
 [13 18 24]
 [28 20 17]]
[[ -9 -11  -3]
 [-13  -2  -6]
 [-10 -16 -13]]
[[ 10 152  88]
 [  0  80 135]
 [171  36  30]]
[[0.1        0.42105263 0.72727273]
 [0.         0.8        0.6       ]
 [0.47368421 0.11111111 0.13333333]]


Array Manipulation

In [40]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 1 5]
 [1 5 4]]
(2, 3)


In [41]:
#transpose
trans= np.transpose(array)
print(trans)
print(trans.shape)

[[2 1]
 [1 5]
 [5 4]]
(3, 2)


In [42]:
#reshape
a= np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[1 6 8]
 [6 2 8]]
(2, 3)


In [43]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[1 6]
 [8 6]
 [2 8]]
(3, 2)


#Pandas Library:
Useful for Data Processing & Analysis


> Pandas Dataframe:
Pandas DataFrame is two-dimensional tabular data structure with labed axes(rows and cols)



In [44]:
#importing pandas library
import pandas as pd

Creating a pandas dataframe

In [47]:
#pandas dataframe
boston_df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')

In [48]:
boston_df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [49]:
boston_df.shape

(506, 14)

In [50]:
type(boston_df)

pandas.core.frame.DataFrame

In [51]:
diabetes_df=pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv')

In [52]:
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [54]:
diabetes_df.shape

(768, 9)

Loading the data from a excel file to a pandas dataframe

In [58]:
boston_df.tail()

crim   zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
501  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273     21.0   
504  0.10959  0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273     21.0   
505  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273     21.0   

          b  lstat  medv  
501  391.99   9.67  22.4  
502  396.90   9.08  20.6  
503  396.90   5.64  23.9  
504  393.45   6.48  22.0  
505  396.90   7.88  11.9

In [59]:
boston_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [60]:
#finding the missing values
boston_df.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [61]:
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [62]:
#counting the value based on the labels
diabetes_df.value_counts('Outcome')

Outcome
0    500
1    268
Name: count, dtype: int64

In [63]:
#group the value based on the mean
diabetes_df.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [64]:
#count number of values
boston_df.count()

crim       506
zn         506
indus      506
chas       506
nox        506
rm         506
age        506
dis        506
rad        506
tax        506
ptratio    506
b          506
lstat      506
medv       506
dtype: int64

In [65]:
#mean value for each col
boston_df.mean()

crim         3.613524
zn          11.363636
indus       11.136779
chas         0.069170
nox          0.554695
rm           6.284634
age         68.574901
dis          3.795043
rad          9.549407
tax        408.237154
ptratio     18.455534
b          356.674032
lstat       12.653063
medv        22.532806
dtype: float64

In [66]:
#standard deviation-- col wise
boston_df.std()

crim         8.601545
zn          23.322453
indus        6.860353
chas         0.253994
nox          0.115878
rm           0.702617
age         28.148861
dis          2.105710
rad          8.707259
tax        168.537116
ptratio      2.164946
b           91.294864
lstat        7.141062
medv         9.197104
dtype: float64

In [67]:
#min val
boston_df.min()

crim         0.00632
zn           0.00000
indus        0.46000
chas         0.00000
nox          0.38500
rm           3.56100
age          2.90000
dis          1.12960
rad          1.00000
tax        187.00000
ptratio     12.60000
b            0.32000
lstat        1.73000
medv         5.00000
dtype: float64

In [68]:
#max value
boston_df.max()

crim        88.9762
zn         100.0000
indus       27.7400
chas         1.0000
nox          0.8710
rm           8.7800
age        100.0000
dis         12.1265
rad         24.0000
tax        711.0000
ptratio     22.0000
b          396.9000
lstat       37.9700
medv        50.0000
dtype: float64

In [69]:
boston_df.describe()

crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio           b  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat        medv  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [75]:
#removing the row,give axis value 0
boston_df.drop(index=0,axis=0)  #

crim   zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
1    0.02731  0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2    0.02729  0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3    0.03237  0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4    0.06905  0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   
5    0.02985  0.0   2.18     0  0.458  6.430  58.7  6.0622    3  222     18.7   
..       ...  ...    ...   ...    ...    ...   ...     ...  ...  ...      ...   
501  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273     21.0   
504  0.10959  0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273     21.0   
505  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273     21.0   

          b  lstat  medv  Price  
1    396.90   9.14  21.6   21.6  
2    392.83   4.03  34.7   34.7  
3    394.63   2.94  33.4   33.4  
4    396.90   5.33  36.2   36.2  
5    394.12   5.21  28.7   28.7  
..      ...    ...   ...    ...  
501  391.99   9.67  22.4   22.4  
502  396.90   9.08  20.6   20.6  
503  396.90   5.64  23.9   23.9  
504  393.45   6.48  22.0   22.0  
505  396.90   7.88  11.9   11.9  

[505 rows x 15 columns]

In [82]:
#drop a col
boston_df.drop(columns='zn',axis=1)

crim  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0    0.00632   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1    0.02731   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2    0.02729   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3    0.03237   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4    0.06905   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   
..       ...    ...   ...    ...    ...   ...     ...  ...  ...      ...   
501  0.06263  11.93     0  0.573  6.593  69.1  2.4786    1  273     21.0   
502  0.04527  11.93     0  0.573  6.120  76.7  2.2875    1  273     21.0   
503  0.06076  11.93     0  0.573  6.976  91.0  2.1675    1  273     21.0   
504  0.10959  11.93     0  0.573  6.794  89.3  2.3889    1  273     21.0   
505  0.04741  11.93     0  0.573  6.030  80.8  2.5050    1  273     21.0   

          b  lstat  medv  Price  
0    396.90   4.98  24.0   24.0  
1    396.90   9.14  21.6   21.6  
2    392.83   4.03  34.7   34.7  
3    394.63   2.94  33.4   33.4  
4    396.90   5.33  36.2   36.2  
..      ...    ...   ...    ...  
501  391.99   9.67  22.4   22.4  
502  396.90   9.08  20.6   20.6  
503  396.90   5.64  23.9   23.9  
504  393.45   6.48  22.0   22.0  
505  396.90   7.88  11.9   11.9  

[506 rows x 14 columns]

In [83]:
#locating a row using index val
boston_df.iloc[2]

crim         0.02729
zn           0.00000
indus        7.07000
chas         0.00000
nox          0.46900
rm           7.18500
age         61.10000
dis          4.96710
rad          2.00000
tax        242.00000
ptratio     17.80000
b          392.83000
lstat        4.03000
medv        34.70000
Price       34.70000
Name: 2, dtype: float64

In [84]:
#locating a particular col
print(boston_df.iloc[:,0]) #first col

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: crim, Length: 506, dtype: float64


In [85]:
print(boston_df.iloc[:,1]) #sec col

0      18.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
501     0.0
502     0.0
503     0.0
504     0.0
505     0.0
Name: zn, Length: 506, dtype: float64


Correlation:


1.   Positive Correlation
2.   negative Correation




In [86]:
boston_df.corr()

crim        zn     indus      chas       nox        rm       age  \
crim     1.000000 -0.200469  0.406583 -0.055892  0.420972 -0.219247  0.352734   
zn      -0.200469  1.000000 -0.533828 -0.042697 -0.516604  0.311991 -0.569537   
indus    0.406583 -0.533828  1.000000  0.062938  0.763651 -0.391676  0.644779   
chas    -0.055892 -0.042697  0.062938  1.000000  0.091203  0.091251  0.086518   
nox      0.420972 -0.516604  0.763651  0.091203  1.000000 -0.302188  0.731470   
rm      -0.219247  0.311991 -0.391676  0.091251 -0.302188  1.000000 -0.240265   
age      0.352734 -0.569537  0.644779  0.086518  0.731470 -0.240265  1.000000   
dis     -0.379670  0.664408 -0.708027 -0.099176 -0.769230  0.205246 -0.747881   
rad      0.625505 -0.311948  0.595129 -0.007368  0.611441 -0.209847  0.456022   
tax      0.582764 -0.314563  0.720760 -0.035587  0.668023 -0.292048  0.506456   
ptratio  0.289946 -0.391679  0.383248 -0.121515  0.188933 -0.355501  0.261515   
b       -0.385064  0.175520 -0.356977  0.048788 -0.380051  0.128069 -0.273534   
lstat    0.455621 -0.412995  0.603800 -0.053929  0.590879 -0.613808  0.602339   
medv    -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   
Price   -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   

              dis       rad       tax   ptratio         b     lstat      medv  \
crim    -0.379670  0.625505  0.582764  0.289946 -0.385064  0.455621 -0.388305   
zn       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445   
indus   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725   
chas    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260   
nox     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321   
rm       0.205246 -0.209847 -0.292048 -0.355501  0.128069 -0.613808  0.695360   
age     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955   
dis      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929   
rad     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626   
tax     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536   
ptratio -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787   
b        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461   
lstat   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663   
medv     0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000   
Price    0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000   

            Price  
crim    -0.388305  
zn       0.360445  
indus   -0.483725  
chas     0.175260  
nox     -0.427321  
rm       0.695360  
age     -0.376955  
dis      0.249929  
rad     -0.381626  
tax     -0.468536  
ptratio -0.507787  
b        0.333461  
lstat   -0.737663  
medv     1.000000  
Price    1.000000